trigger:
  - main

pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'

  - script: |
      npm install
      npm run build
      echo "현재 디렉토리:"
      pwd
      echo "디렉토리 내용:"
      ls -la
    displayName: 'Install and build React project'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'build'
      api_location: ''
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      skip_app_build: true
